language: java
before_script:
  - unset GEM_PATH GEM_HOME IRBRC
  - "export PATH=`pwd`/bin:$PATH"

jdk:
  - oraclejdk7
  
service_name: travis-pro
	repo_token: pG1Z8lXw8yULzfiFGpeNZIYSM65aq7DsV